mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  env_file: test.env
  environment:
    - LANG=C.UTF-8
    - TERM=dumb
jenkins:
  image: jenkins:1.625.3
  ports:
    - "8080:8080"
  volumes:
    - /Users/Thoughtworks/works/docker-cached/jenkins_home:/var/jenkins_home
  links:
    - mysql
  environment:
    - LANG=C.UTF-8
    - TERM=dumb
redis:
  image: redis:3.0.7
  ports:
    - "6379:6379"
  volumes:
    - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
nginx:
  build: ./nginx
  ports:
    - "80:80"
  environment:
    - LANG=C.UTF-8
    - TERM=dumb
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - /Users/Thoughtworks/works/docker-cached/nginx_fs:/var/fs