ambassador:
    image: cpuguy83/docker-grand-ambassador
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "-name assembly_node-app_1 -name assembly_jenkins-nodejs_1 -name assembly_node-task-queue_1"
mysql:
  image: mysql:5.7
  ports:
    - 3306:3306
  env_file:
    - ./production.env
  volumes:
    - ./mysql/create-db.sh:/tmp/create-db.sh
  ports:
    - "3306:3306"
jetty-api:
  image: jetty:9.3
  volumes:
    - ./assemble/jetty-api:/var/lib/jetty/webapps
  links:
    - mysql:mysql
    - ambassador:node-app
mongodb:
  image: mongo:3.2
node-app:
  image: node:5.8
  ports:
    - "3000:3000"
  volumes:
    - ./assemble/node-app:/var/app
  command: bash -c "cd /var/app && node app.js"
  links:
    - mongodb:mongodb
    - jetty-api:jetty-api
    - nginx:nginx
    - ambassador:node-task-queue
  env_file:
    - ./production.env
redis:
  image: redis:3.0.7
  volumes:
    - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
node-task-queue:
  image: node:5.8
  volumes:
    - ./assemble/task-queue:/var/app
  command: bash -c "cd /var/app && node app.js"
  links:
    - redis:redis
    - ambassador:jenkins-nodejs
    - nginx:nginx
    - ambassador:node-app
  env_file:
    - ./production.env
  ports:
    - "4000:4000"
nginx:
  image: nginx:1.9
  env_file:
    - ./production.env
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - /home/ubuntu/works/docker-cached/nginx_fs:/var/fs
jenkins-nodejs:
  build: ./jenkins-nodejs
  links:
    - nginx:nginx
    - ambassador:node-task-queue
  env_file:
    - ./production.env
  ports:
    - "18080:8080"
